project:
  type: website
  output-dir: docs

website:
  title: "NatSci Project"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - moreQuestions.qmd
      - href: https://numbas.mathcentre.ac.uk/
        text: Explore NUMBAS

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

